### ISSUE TITLE
Epic: Update to latest Noir

### ISSUE THREAD

**Issue by Savio-Sou** [TomAFrench/acvm-backend-groth16#1]
Reasoning:
- Interest from the Noir community
  - https://discord.com/channels/1113924620781883405/1237701150204100668/1237701150204100668
  - https://discord.com/channels/1113924620781883405/1226466915875295288/1227334773534490687
  - https://discord.com/channels/1113924620781883405/1113924622031798313/1183506728806002729
- Useful for building reference implementations of ZK Celestia Improvement Proposals
  - https://github.com/celestiaorg/CIPs/pull/91

Tasks
- [ ] Bump ACVM version
- [ ] Strip out everything from backend except the contents of proof_system.rs
- [ ] Grab the mock backend CLI interface and hook it up to existing functions

**Comment by Savio-Sou** [comment]
Action items could change following https://github.com/noir-lang/noir/issues/4960.
